import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Portfolio</title>
				<meta name="description" content="Generated by issam" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="text-4xl underline text-red-500 text-text2">
				hello world
			</h1>
		</div>
	);
}
